### ISSUE TITLE
Update Game class and its children

### ISSUE THREAD

**Issue by ghost** [MSAlih1/RiotApiCaller#6]
BUG FIX REQUEST

- [Game Ids Update,  subType enums Update] 

**Game Ids Update** 
GameIds now > 2^31 (positive integer max). `JsonConvert` throws the following exception:  

> {"JSON integer 2524678113 is too large or small for an Int32. Path 'games[0].gameId', line 1, position 52."} 

- note that 2524678113 > 2^31.

`fixed by changing GameID to long.`

**subType enums Update**
Subtype needs updating, as it seems new subtypes have been added.  Trying to make a call to recent games led to the following exception: 

> {"Error converting value \"RANKED_FLEX_SR\" to type 'System.Nullable`1[RiotCaller.Enums.subType]'. Path 'games[7].subType', line 1, position 12838."}

`Search API for new subtypes, and at a minum add RANKED_FLEX_SR to subtype API.`

**Comment by msx752** [comment]
@ianmakecode Thanks for the notify and sorry for the late answer. new api v3 is ready for .netcore 1.1 framework, so this library will not be  updated.

RiotGames NEW API V3 : https://github.com/msx752/RiotGamesApi.AspNetCore
